### ISSUE TITLE
Automatic a/r for Image and video

### ISSUE THREAD

**Issue by ale-grosselle** [albertodeago/vue-aspect-ratio#1]
Hi @albertodeago,
Is It possible to pass an image or video as prop and the component automatically  handle the aspect ratio?

In addition I could add (Always as prop) the fixed size (w o h).

**Comment by albertodeago** [comment]
Hi @ale-grosselle, thanks for reaching out.

I'm not sure to understand what you are asking for. In plain html/css if you put an image element with a 16:9 aspect ratio source, the image will already follow this aspect ratio (pretty sure it's the same for video)

JsFiddle example: https://jsfiddle.net/2jz8uro3/

Can you explain or show me an example?

**Comment by ale-grosselle** [comment]
My fault you have completely reason; I was convinced that the video tag element could not independently calculate the width using the video aspect ratio:
https://codepen.io/ale-grosselle/pen/rNaMpBQ

**Comment by albertodeago** [comment]
No problem at all!
