### ISSUE TITLE
No SSR

### ISSUE THREAD

**Issue by dimitriaatos** [albertodeago/vue-aspect-ratio#3]
Document is referenced in the dist files, not sure why is that, it prevents vue-aspect-ratio from being rendered on the server.

https://github.com/albertodeago/vue-aspect-ratio/blob/a3ceead208c7bafd8f218267b2d0c61d13e0fc57/dist/vue-aspect-ratio.common.js#L225

**Comment by dimitriaatos** [comment]
Using the component from the source folder seems to work.
```javascript
import VueAspectRatio from 'vue-aspect-ratio/src/AspectRatio.vue'
```

**Comment by albertodeago** [comment]
Thanks for the report, I never tried with SSR, i'll have a look

**Comment by albertodeago** [comment]
Looks like the issue has something to do with the vue-cli build. I think it searches for the document head to inject the style.
Some simple solutions could be inlining the style (but it will be super hard to override if needed) or to expose a separate css file to import (but I find a bit weird for just a component).
I'll dig a bit deeper
