### ISSUE TITLE
Available in vue 3?

### ISSUE THREAD

**Issue by superdiazzz** [albertodeago/vue-aspect-ratio#4]
I'm on vue3 project

**Comment by albertodeago** [comment]
Thanks, seems like you're right, I've tested it and at the moment it doesn't work.
I'll try to make it work with vue3

**Comment by albertodeago** [comment]
So, honestly, I'm not sure why this doesn't work on Vue3, I'm not using anything particular or something that involved a breaking change... I'll dig into deeper...
Meanwhile, you can still use it by pointing to the component source (that's working with vue3 indeed)

so for example import it like
```js
import vue-aspect-ratio from "vue-aspect-ratio/src/AspectRatio.vue";
```

Hope this helps @superdiazzz

**Comment by superdiazzz** [comment]
> So, honestly, I'm not sure why this doesn't work on Vue3, I'm not using anything particular or something that involved a breaking change... I'll dig into deeper... Meanwhile, you can still use it by pointing to the component source (that's working with vue3 indeed)
> 
> so for example import it like
> 
> ```js
> import VueAspectRatio from "vue-aspect-ratio/src/AspectRatio.vue";
> ```
> 
> Hope this helps @superdiazzz

Hi @albertodeago i have solved by re-scripting your code in my local side. Thanks for your work i appreciate it

**Comment by albertodeago** [comment]
@superdiazzz just a tip, if you don't need to support IE11 check [aspect-ratio css property](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) out
